spring.application.name=Physioplus

spring.data.mongodb.booking.uri=${MONGODB_URI}
spring.data.mongodb.payment.uri=${MONGODB_URI}
spring.data.mongodb.doctor.uri=${MONGODB_URI}
spring.data.mongodb.patient.uri=${MONGODB_URI}

# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=doctor_booking_db

server.port=8080